project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Ideal-Point Estimation in the 20th German Bundestag"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Analysis
